### ISSUE TITLE
Time filtering is getting scaled up

### ISSUE THREAD

**Issue by KingBoomie** [KristerV/HNSince#9] opened 2021-02-12 09:02 UTC
![Screenshot_20210212-105146](https://user-images.githubusercontent.com/6442206/107748002-0c248380-6d21-11eb-92b9-d230871f07c1.jpg)
![Screenshot_20210212-105453](https://user-images.githubusercontent.com/6442206/107748006-0d55b080-6d21-11eb-86a0-ae31237514c3.jpg)

For some reason, posts that are shown do not correspond to the time period they should be filtered for.
E.G first picture - expected to only see posts that are max 14h old. Saw posts that were even more than 1 month old.

**Comment by KristerV** [comment] 2021-02-13 09:20
omg what a fail on my part. Looking into this.

**Comment by KristerV** [comment] 2021-02-13 10:22
was the first picture taken after you had visited in a few days or was the 14h correctly when you last visited?

I'm writing tests here and the behaviour seems correct. But perhaps the time in the title is wrong actually.

**Comment by KristerV** [comment] 2021-02-13 10:24
scratch that. I'm having the issue too and the title is correct.

![image](https://user-images.githubusercontent.com/2750622/107847712-0cd71b80-6dee-11eb-8a52-38f2e080eeef.png)

**Comment by KristerV** [comment] 2021-02-13 16:56
This is a hard problem to reproduce. But I did find a major mishap in the code. So _should_ be fixed. Can you confirm?

**Comment by KingBoomie** [comment] 2021-02-13 20:28
It seems to work. But it seemed to work yesterday too. Since there isn't a
good reproduction the best one can do is to hope the bug is gone.

**Comment by KristerV** [comment] 2021-02-14 11:33
yeah I actually wrote tests and couldn't reproduce the bug :D but I did find clues in the database and did fix a pretty critical issue.

I'll close this for now. If you find the bug again post a screenshot and I'll reopen. Thanks for reporting!

**Closed as completed by KristerV** 2021-02-14 11:33 UTC
